name: Run pully
description: Runs pully, a little utility to write one slack message per pr that is constantly edited when the status changes.

# TODO input to tune what to do on draft (dont post, remove message, etc)
# TODO input to tune what to do on closed (not merged. Remove the message? Allow reposting later?)

# TODO secret input? Is it even defined in the interface...?

runs:
  using: "node20"
  main: dist/index.js
