name: Pully reminder

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  remind:
    runs-on: ubuntu-latest
    name: Post reminder on PRs awaiting review
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: N35N0M/pully@512c31f20109066a1d9a5912b3187a68e1ddfe7b
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULLY_SLACK_CHANNEL: ${{ secrets.PULLY_SLACK_CHANNEL }}
          PULLY_SLACK_TOKEN: ${{ secrets.PULLY_SLACK_TOKEN }}
